export enum ErrorMessage {
  EMAIL_EXISTS = "Email already exists",
  USERNAME_EXISTS = "Username already exists",
  REGISTRATION_FAILED = "Registration failed",
  INVALID_CREDENTIALS = "Invalid credentials",
  LOGIN_FAILED = "Login failed",
  UNAUTHORIZED = "Unauthorized",
  TOKEN_REQUIRED = "Token required",
  INVALID_OR_EXPIRED_TOKEN = "Invalid or expired token",
  USER_NOT_FOUND = "User not found",
  FAILED_TO_FETCH_PROFILE = "Failed to fetch profile",
  FAILED_TO_FETCH_USER = "Failed to fetch user",
  FAILED_TO_UPDATE_PROFILE = "Failed to update profile",
  JWT_SECRET_NOT_DEFINED = "JWT_SECRET is not defined",
  INVALID_MEMBER_IDS = "One or more member IDs are invalid",
  FAILED_TO_CREATE_CONVERSATION = "Failed to create conversation",
  FAILED_TO_FETCH_CONVERSATIONS = "Failed to fetch conversations",
  DIRECT_CONVERSATION_EXISTS = "Direct conversation between these users already exists",
}